name: 'Frontend CI'

on:
  push:
    
defaults:
  run:
    working-directory: frontend/gostarkme-web

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup node'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'frontend/gostarkme-web/.nvmrc'
          cache-dependency-path: frontend/gostarkme-web/package-lock.json

      - name: 'Install dependencies'
        run: |
          cd frontend/gostarkme-web 
          npm ci
      
      - name: 'Build typescript'
        run: npm run build

      - name: 'Run dev'
        run:  npm run dev