name: 'Frontend CI'

on:
  push:
    
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend/gostarkme-web
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup node'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'frontend/gostarkme-web/.nvmrc'
          cache-dependency-path: frontend/gostarkme-web/package-lock.json

      - name: 'Install dependencies'
        run: npm ci
        working-directory: ${{env.working-directory}}
      
      - name: 'Build typescript'
        run: npm run build
        working-directory: ${{env.working-directory}}

      - name: 'Run dev'
        run:  npm run dev
        working-directory: ${{env.working-directory}}